apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: greeter-server
    k8s-app-project: demo
  name: greeter-server
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: greeter-server
      k8s-app-project: demo
  template:
    metadata:
      labels:
        k8s-app: greeter-server
        k8s-app-project: demo
      name: greeter-server
    spec:
      containers:
        - command:
            - /server/app
          image: yeqown/lb-client.server:v1.0.0
          imagePullPolicy: IfNotPresent
          name: server
          resources:
            limits:
              cpu: "0.1"
              memory: 100Mi
            requests:
              cpu: "0.1"
              memory: 100Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: greeter-server
  name: greeter-server
spec:
  clusterIP: None # Headless service
  ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
  selector:
    k8s-app: greeter-server
    k8s-app-project: demo